name: Infection
version: 1.1
author: Aylias
main: me.aylias.minecraft.plugins.edgecut.infection.Main
depend: [APTLib]
api-version: 1.15
commands:
  start:
    usage: /<command>
  zombie:
    usage: /<command> <player>
  staff:
    usage: /<command> <player>
  reset:
    usage: /<command>
  endcrate:
    usage: /<command>
  human:
    usage: /<command>